cliente_index:
    path:     /
    defaults: { _controller: "AppBundle:Cliente:index" }
    methods:  GET

cliente_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cliente:show" }
    methods:  GET

cliente_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cliente:new" }
    methods:  [GET, POST]

cliente_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cliente:edit" }
    methods:  [GET, POST]

cliente_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cliente:delete" }
    methods:  DELETE
    
cliente_state:
    path:     /{id}/changestate
    defaults: { _controller: "AppBundle:Cliente:changestate" }
    methods:  GET    
